/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2017-02-12 20:09:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.company;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class secondregisterhotel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1486357534094L));
    _jspx_dependants.put("jar:file:/C:/Users/User/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Hotel-reserve-project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/board.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/layout.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\t<section>\r\n");
      out.write("\t<form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/company/register.do\">\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t\t<h2>숙소 등록</h2>\r\n");
      out.write("\t\t<hr width=\"80%\" /><br/>\r\n");
      out.write("\t\t<table width=\"70%\">\r\n");
      out.write("\t\t\t<tr width=\"30%\">\r\n");
      out.write("\t\t\t\t<td>일반 사항</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"basic\" value=\"장애인 편의시설\"/>&nbsp; 장애인 편의시설&nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"basic\" value=\"에어컨\"/>&nbsp; 에어컨&nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"basic\" value=\"금연실\"/>&nbsp; 금연실&nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"basic\" value=\"헤어드라이어\"/>&nbsp; 헤어드라이어&nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"basic\" value=\"TV\"/>&nbsp; TV&nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"basic\" value=\"데스크\"/>&nbsp; 데스크&nbsp;<br/>\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"basic\" value=\"장애인 주차시설\"/>&nbsp; 장애인 주차시설&nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"basic\" value=\"스위트룸\"/>&nbsp; 스위트룸&nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"basic\" value=\"개인욕실\"/>&nbsp; 개인욕실&nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"basic\" value=\"비데\"/>&nbsp; 비데&nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"basic\" value=\"자판기\"/>&nbsp; 자판기&nbsp;\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>편의 시설</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"convenience\" value=\"사우나\"/>&nbsp; 사우나\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"convenience\" value=\"정원\"/>&nbsp; 정원\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"convenience\" value=\"거주지\"/>&nbsp; 거주지\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"convenience\" value=\"피트니스센터\"/>&nbsp; 피트니스센터\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"convenience\" value=\"수영장\"/>&nbsp; 수영장\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"convenience\" value=\"마사지/관리 샵\"/>&nbsp; 마사지/관리 샵\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>서비스</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"service\" value=\"비즈니스센터\"/>&nbsp; 비즈니스센터\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"service\" value=\"컨시어지 서비스\"/>&nbsp; 컨시어지 서비스\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"service\" value=\"투어 데스크\"/>&nbsp; 투어 데스크\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"service\" value=\"엘리베이터\"/>&nbsp; 엘리베이터<br/>\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"service\" value=\"24시간 리셉션\"/>&nbsp; 24시간 리셉션\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"service\" value=\"컨퍼런스룸\"/>&nbsp; 컨퍼런스룸\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"service\" value=\"환전\"/>&nbsp; 환전\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"service\" value=\"외국어 구사직원\"/>&nbsp; 외국어 구사직원\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"service\" value=\"안전금고\"/>&nbsp; 안전금고<br/>\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"service\" value=\"모닝콜 서비스\"/>&nbsp; 모닝콜 서비스\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"service\" value=\"회의실\"/>&nbsp; 회의실\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"service\" value=\"복사기\"/>&nbsp; 복사기\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"service\" value=\"물품 보관소\"/>&nbsp; 물품 보관소\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"service\" value=\"흡연구역\"/>&nbsp; 흡연구역\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>인터넷</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"internet\" value=\"무선인터넷\"/>&nbsp; 무선인터넷\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>주차</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"parking\" value=\"무료주차장\"/>&nbsp; 무료주차장\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"parking\" value=\"공항 셔틀버스 제공\"/>&nbsp; 공항 셔틀버스 제공\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"parking\" value=\"발렛파킹\"/>&nbsp; 발렛파킹\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>체크인</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<select name=\"check-in\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"9:00\">9:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"10:00\">10:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"11:00\">11:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"12:00\">12:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"13:00\">13:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"14:00\" selected=\"selected\">14:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"15:00\">15:00</option>\r\n");
      out.write("\t\t\t\t\t</select> 이후\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>체크아웃</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<select name=\"check-out\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"9:00\">9:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"10:00\">10:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"11:00\">11:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"12:00\" selected=\"selected\">12:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"13:00\">13:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"14:00\">14:00</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"15:00\">15:00</option>\r\n");
      out.write("\t\t\t\t\t</select> 이전\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table><br/>\r\n");
      out.write("\t\t<input type=\"submit\" value=\" 다음으로 \"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/jsp/company/secondregisterhotel.jsp(14,2) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("/include/topmenu.do");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/jsp/company/secondregisterhotel.jsp(118,2) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("/include/footer.do");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
    }
    return false;
  }
}
