/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2017-02-27 05:45:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Map;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Test7_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script language=\"javascript\"\r\n");
      out.write("\tsrc=\"https://apis.skplanetx.com/tmap/js?version=1&format=javascript&appKey=bac4f916-3297-3be4-93ff-e37ae88b8f42\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t//초기화 함수\r\n");
      out.write("\tfunction initTmap() {\r\n");
      out.write("\t\tcenterLL = new Tmap.LonLat(14145677.4, 4511257.6);\r\n");
      out.write("\t\tmap = new Tmap.Map({\r\n");
      out.write("\t\t\tdiv : 'map_div',\r\n");
      out.write("\t\t\twidth : '100%',\r\n");
      out.write("\t\t\theight : '400px',\r\n");
      out.write("\t\t\ttransitionEffect : \"resize\",\r\n");
      out.write("\t\t\tanimation : true\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tsearchRoute();\r\n");
      out.write("\t}\r\n");
      out.write("\t//경로 정보 로드\r\n");
      out.write("\tfunction searchRoute() {\r\n");
      out.write("\r\n");
      out.write("\t\tvar form = document.inputForm;\r\n");
      out.write("\t\tvar routeFormat = new Tmap.Format.KML({\r\n");
      out.write("\t\t\textractStyles : true,\r\n");
      out.write("\t\t\textractAttributes : true\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tvar startX = form.startlon.value;\r\n");
      out.write("\t\tvar startY = form.startlat.value;\r\n");
      out.write("\t\tvar endX = form.endlon.value;\r\n");
      out.write("\t\tvar endY = form.endlat.value;\r\n");
      out.write("\t\tvar urlStr = \"https://apis.skplanetx.com/tmap/routes?version=1&format=xml\";\r\n");
      out.write("\t\turlStr += \"&startX=\" + startX;\r\n");
      out.write("\t\turlStr += \"&startY=\" + startY;\r\n");
      out.write("\t\turlStr += \"&endX=\" + endX;\r\n");
      out.write("\t\turlStr += \"&endY=\" + endY;\r\n");
      out.write("\t\turlStr += \"&appKey=bac4f916-3297-3be4-93ff-e37ae88b8f42\"; \r\n");
      out.write("\t\tvar prtcl = new Tmap.Protocol.HTTP({\r\n");
      out.write("\t\t\turl : urlStr,\r\n");
      out.write("\t\t\tformat : routeFormat\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tvar routeLayer = new Tmap.Layer.Vector(\"route\", {\r\n");
      out.write("\t\t\tprotocol : prtcl,\r\n");
      out.write("\t\t\tstrategies : [ new Tmap.Strategy.Fixed() ]\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\trouteLayer.events\r\n");
      out.write("\t\t\t\t.register(\"featuresadded\", routeLayer, onDrawnFeatures);\r\n");
      out.write("\t\tmap.addLayer(routeLayer);\r\n");
      out.write("\t}\r\n");
      out.write("\t//경로 그리기 후 해당영역으로 줌\r\n");
      out.write("\tfunction onDrawnFeatures(e) {\r\n");
      out.write("\t\tmap.zoomToExtent(this.getDataExtent());\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.onload = function(){\r\n");
      out.write("\t\tinitTmap();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form name=\"inputForm\">\r\n");
      out.write("\t\t<div id=\"map_div\"></div>\r\n");
      out.write("\t\t출발지<br /> 위도 : <input type=\"text\" name=\"startlon\" /><br /> 경도 : <input\r\n");
      out.write("\t\t\ttype=\"text\" name=\"startlat\" /><br /> <br /> 도착지<br /> 위도 : <input\r\n");
      out.write("\t\t\ttype=\"text\" name=\"endlon\" /><br /> 경도 : <input type=\"text\"\r\n");
      out.write("\t\t\tname=\"endlat\" /><br /> <input type=\"button\" value=\" 경로보기\"\r\n");
      out.write("\t\t\tonclick=\"script:initTmap()\" />\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
