/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2017-03-03 02:39:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Map;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Tmap4_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("#rightside {\r\n");
      out.write("\tposition: static;\r\n");
      out.write("\twidth: 500px;\r\n");
      out.write("\theight: 500px;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tfont-size: 10pt;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://code.jquery.com/jquery-1.12.3.min.js\"></script>\r\n");
      out.write("<script language=\"javascript\"\r\n");
      out.write("\tsrc=\"https://apis.skplanetx.com/tmap/js?version=1&format=javascript&appKey=8119ac79-8052-3455-96b6-0595b08be4d7\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar startX, startY, endX, endY;\r\n");
      out.write("\tvar map, lonlat, zoom;\r\n");
      out.write("\tvar routeLayer;\r\n");
      out.write("\r\n");
      out.write("\tvar f = 0;\r\n");
      out.write("\tfunction flag() {\r\n");
      out.write("\t\tf = !f;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar markers = new Tmap.Layer.Markers( \"MarkerLayer\" );\r\n");
      out.write("\t\r\n");
      out.write("\tfunction initTmap() {\r\n");
      out.write("\t\tcenterLL = new Tmap.LonLat(14145677.4, 4511257.6);\r\n");
      out.write("\t\tmap = new Tmap.Map({\r\n");
      out.write("\t\t\tdiv : 'map_div',\r\n");
      out.write("\t\t\twidth : '500px',\r\n");
      out.write("\t\t\theight : '500px',\r\n");
      out.write("\t\t\ttransitionEffect : \"resize\",\r\n");
      out.write("\t\t\tanimation : true\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tmap.addLayer(markers);\r\n");
      out.write("\t}; \r\n");
      out.write("\t//경로 정보 로드\r\n");
      out.write("\tfunction searchRoute() {\r\n");
      out.write("\t\tif(routeLayer != null){\r\n");
      out.write("\t\t\tmap.removeLayer(routeLayer);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tmarkers.destroy();\r\n");
      out.write("\t\tvar routeFormat = new Tmap.Format.KML({\r\n");
      out.write("\t\t\textractStyles : true,\r\n");
      out.write("\t\t\textractAttributes : true\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar urlStr = \"https://apis.skplanetx.com/tmap/routes?version=1&format=xml\";\r\n");
      out.write("\t\turlStr += \"&startX=\" + startX;\r\n");
      out.write("\t\turlStr += \"&startY=\" + startY;\r\n");
      out.write("\t\turlStr += \"&endX=\" + endX;\r\n");
      out.write("\t\turlStr += \"&endY=\" + endY;\r\n");
      out.write("\t\turlStr += \"&appKey=bac4f916-3297-3be4-93ff-e37ae88b8f42\";\r\n");
      out.write("\t\tvar prtcl = new Tmap.Protocol.HTTP({\r\n");
      out.write("\t\t\turl : urlStr,\r\n");
      out.write("\t\t\tformat : routeFormat\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\trouteLayer = new Tmap.Layer.Vector(\"route\", {\r\n");
      out.write("\t\t\tprotocol : prtcl,\r\n");
      out.write("\t\t\tstrategies : [ new Tmap.Strategy.Fixed() ]\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\trouteLayer.events.register(\"featuresadded\", routeLayer, onDrawnFeatures);\r\n");
      out.write("\t\tconsole.log(routeLayer);\r\n");
      out.write("\t\tf=0;\r\n");
      out.write("\t\tmap.addLayer(routeLayer);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//경로 그리기 후 해당영역으로 줌\r\n");
      out.write("\tfunction onDrawnFeatures(e) {\r\n");
      out.write("\t\t$('#addinfo').children().remove();\r\n");
      out.write("\t\tmap.zoomToExtent(this.getDataExtent());\r\n");
      out.write("\t\tfor(var i=0; i<routeLayer.features.length; i++){\r\n");
      out.write("\t\t\t$('#addinfo').append('<div>'+(i+1)+'. '+routeLayer.features[i].attributes.description+'<br/></div>');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\twindow.onload = function() {\r\n");
      out.write("\t\tinitTmap();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction dragStart(event) {\r\n");
      out.write("\t\tevent.dataTransfer.effectAllowed = 'move';\r\n");
      out.write("\t\tevent.dataTransfer.setData(\"Text\", event.target.getAttribute('id'));\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction dragEnter(event) {\r\n");
      out.write("\t\tvar idelt = event.dataTransfer.getData(\"Text\");\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction dragOver(event) {\r\n");
      out.write("\t\tvar idelt = event.dataTransfer.getData(\"Text\");\r\n");
      out.write("\t\tvar id = event.target.getAttribute('id');\r\n");
      out.write("\t\tif (id == 'div_map' && idelt == drag) {\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction dragDrop(event) {\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction startDragEnd(event) {\r\n");
      out.write("\t\tf = 1;\r\n");
      out.write("\t\tif (f==1) {\r\n");
      out.write("\t\t\tmap.events.register(\"mouseover\", map, onClickMap);\r\n");
      out.write("\t\t\tevent.dataTransfer.clearData(\"Text\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction EndDragEnd(event){\r\n");
      out.write("\t\tf = 2;\r\n");
      out.write("\t\tif (f==2) {\r\n");
      out.write("\t\t\tmap.events.register(\"mouseover\", map, onClickMap1);\r\n");
      out.write("\t\t\tevent.dataTransfer.clearData(\"Text\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction onClickMap(e) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (f!=1) {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tlonlat = map.getLonLatFromViewPortPx(e.xy);\r\n");
      out.write("\t\tlonlat = new Tmap.LonLat(lonlat.lon, lonlat.lat);\r\n");
      out.write("\t\tstartX = lonlat.lon;\r\n");
      out.write("\t\tstartY = lonlat.lat;\r\n");
      out.write("\t\tif(startX != null && startY != null && endX != null && endY != null){\r\n");
      out.write("\t\t\tsearchRoute();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tzoom = 14;\r\n");
      out.write("\r\n");
      out.write("\t\tvar size = new Tmap.Size(24,38);\r\n");
      out.write("\t\tvar offset = new Tmap.Pixel(-(size.w/2), -size.h);\r\n");
      out.write("\t\tvar icon = new Tmap.Icon('https://developers.skplanetx.com/upload/tmap/marker/pin_b_m_a.png',size,offset);\r\n");
      out.write("\t\tvar marker = new Tmap.Markers(lonlat,icon);\r\n");
      out.write("\t\tif (f==1) {\r\n");
      out.write("\t\t\tmarkers.addMarker(marker);\r\n");
      out.write("\t\t\tf = 0;\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction onClickMap1(e) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (f!=2) {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tlonlat = map.getLonLatFromViewPortPx(e.xy);\r\n");
      out.write("\t\tlonlat = new Tmap.LonLat(lonlat.lon, lonlat.lat);\r\n");
      out.write("\t\tendX = lonlat.lon;\r\n");
      out.write("\t\tendY = lonlat.lat;\r\n");
      out.write("\t\tif(startX != null && startY != null && endX != null && endY != null){\r\n");
      out.write("\t\t\tsearchRoute();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tzoom = 14;\r\n");
      out.write("\r\n");
      out.write("\t\tvar size = new Tmap.Size(24,38);\r\n");
      out.write("\t\tvar offset = new Tmap.Pixel(-(size.w/2), -size.h);\r\n");
      out.write("\t\tvar icon = new Tmap.Icon('https://developers.skplanetx.com/upload/tmap/marker/pin_b_m_a.png',size,offset);\r\n");
      out.write("\t\tvar marker = new Tmap.Markers(lonlat,icon);\r\n");
      out.write("\t\tif (f==2) {\r\n");
      out.write("\t\t\tmarkers.addMarker(marker);\r\n");
      out.write("\t\t\tf = 0;\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("<form name=\"inputForm\">\r\n");
      out.write("\t<div id=\"map_div\" style=\"float: left\"\r\n");
      out.write("\t\tondragenter=\"return dragEnter(event)\" \r\n");
      out.write("\t\tondrop=\"return dragDrop(event)\"\r\n");
      out.write("\t\tondragover=\"return dragOver(event)\"></div>\r\n");
      out.write("\t<div id=\"rightside\">\r\n");
      out.write("\t\t&nbsp;\r\n");
      out.write("\t\t<h3>길찾기</h3>\r\n");
      out.write("\t\t<div id=\"dragStart\" draggable=\"true\" \r\n");
      out.write("\t\t\tondragstart=\"return dragStart(event)\"\r\n");
      out.write("\t\t\tondragend=\"return startDragEnd(event)\">\r\n");
      out.write("\t\t\t<img src=\"https://developers.skplanetx.com/upload/tmap/marker/pin_b_m_a.png\" />출발\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"dragEnd\" draggable=\"true\" \r\n");
      out.write("\t\t\tondragstart=\"return dragStart(event)\"\r\n");
      out.write("\t\t\tondragend=\"return EndDragEnd(event)\">\r\n");
      out.write("\t\t\t<img src=\"https://developers.skplanetx.com/upload/tmap/marker/pin_b_m_a.png\" />도착\r\n");
      out.write("\t\t<br/>--------------------------------------------\r\n");
      out.write("\t\t<div id=\"addinfo\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
